### ISSUE TITLE
Modflow 6 and MetaSWAP for disv

### ISSUE THREAD

**Issue by rubencalje** [Deltares/imod_coupler#45]
Great to see that this functionality is open source, and I am interested to use the coupling.

Does the coupling between Modflow 6 and MetaSWAP also work for refined grids using the disv-package of Modflow 6? The technical reference explains the modflow node_nr should be specified, which is further explained as 'the user node number'. However, this addition does not make it much clearer to me.. Can you explain a bit more what this means? Is it the row and column (for dis), the cell2d-number (for disv) or the node number (for disu)? Or is only the dis-package supported, and do I need to calculate a node number from the row and column number?

Thank you for your time!

**Comment by Huite** [comment]
Hi Ruben, glad to hear you're interested!

 I think there are some other colleagues who are able to answer with more detail/precision, but until they check their GitHub notifications (which I think they don't check all that often -- so more likely: when I notify them), to answer with my understanding (this might already be obvious, but also to inform anybody else browsing these pages with similar interests):

1. MetaSWAP is 1D, vertically, with an N:M relation to the MODFLOW cells.
2. There are no principal obstructions to coupling metaSWAP to unstructured models. After all, the connection is purely "vertical" as well.
3. MetaSWAP is capable of outputting data in tabular form, for every soil column. These are text tables.
4. These tables are not very convenient, especially processing the results in the context of an otherwise spatially oriented groundwater model. So quite some time back, IDF output has been added to MetaSWAP, which aggregates multiple columns if needed and writes single values to a raster (IDF).
5. As IDFs are rasters, they are obviously unsuited for DISV topology.

So the "only" thing required to support unstructured MetaSWAP is adding the appropriate IO. This is obviously on the wish list, but hasn't made it to top priority yet. If this is very urgent: it might be possible to tell MetaSWAP to output the tables and skip IDF output. But you'd have to write some post-processing logic for the tables yourself.
Alternatively, it might be possible to use a hack, by tricking MetaSWAP to write into a single row (1D) IDF. You could read this IDF (with e.g. imod-python), discarding the spatial coordinates and just using the values. I think this is possible, if the input files and coupling files are generated appropriately.

At any rate, I'll ping my colleagues now.

**Comment by mjr-deltares** [comment]
Thanks @Huite, for pinging us, and for your elaborate answer!

@rubencalje Does this sufficiently answer your question?

**Comment by rubencalje** [comment]
Thanks for the quick reply. There is no urgency. I was curious about the possibilities, especially as the coupling should in theory be able to handle disv-type grids, like you explain. Right now it is clear to me that only regular grids are supported, although with some hacks it may be possible.

Thanks for your answer, and please let me know if things change!
